stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven
      shellScript: mvn clean package -Dmaven.test.skip=true
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hice-design:latest
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./Deployment.yaml



