stages:
  - name: Build
  steps:
    - runScriptConfig:
        image: jiuxi.harbor.org/stable/maven-3.6.0-jdk-8
        shellScript: mvn clean package -Dmaven.test.skip=true
  - name: publish
  steps:
    - publishImageConfig:
        dockerfilePath: ./Dockerfile
        buildContext: .
        tag: hice-design:latest
  - name: Deploy
  steps:
    - applyYamlConfig:
        path: ./Deployment.yaml
  notification: { }


