stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven
      shellScript: ps aux && pwd && ls -al && mvn clean package -Dmaven.test.skip=true
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: chenkangjie/hice:latest
      registry: 127.0.0.1:34594
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./Deployment.yaml
notification: {}
