apiVersion: apps/v1
kind: Deployment
metadata:
  name: hice-design-deployment
spec:
  selector:
    matchLabels:
      app: hice-design
  replicas: 2
  template:
    metadata:
      labels:
        app: hice-design
    spec:
      containers:
        - name: hice-design
          image: hice-design:latest
          ports:
            - containerPort: 8081