context:
  initializer:
    classes: com.design.hice.initializer.MyInitializer
server:
  port: 8081

sa-token:
  token-name: satoken
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false

spring:
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 120.24.195.151
    # Redis服务器连接端口
    port: 63790
    # Redis服务器连接密码（默认为空）
    password: Miaoyindev123
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hice?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: ckj163737
mybatis:
  mapper-locations: "classpath*:mapper/*.xml"
  configuration:
    mapUnderscoreToCamelCase: true
mapper:
  identity: MYSQL
  enum-as-simple-type: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

---
static:
  path: /opt/homebrew/var/www
spring:
  profiles: dev

---
static:
  path: /usr/local/nginx/html
spring:
  profiles: pro
---
spring:
  profiles:
    active: dev
